<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FacilityInspection</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
	<PackageReference Include="Microsoft.Extensions.Identity.Core" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\EquipmentManagementView.axaml.cs">
      <DependentUpon>EquipmentManagementView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\AdminDashboardView.axaml.cs">
      <DependentUpon>AdminDashboardView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\ScheduleCalendarView.axaml.cs">
      <DependentUpon>ScheduleCalendarView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
